# -------------------------------------------------------------------------------------
# Front Matter Configuration
# See: https://gohugo.io/configuration/front-matter/
# -------------------------------------------------------------------------------------

_merge = "shallow"
lastmod = [
  "lastmod",
  ":git",
  ":fileModTime",
  ":default",
]
