# -------------------------------------------------------------------------------------
# Modules Configuration
# See: https://gohugo.io/configuration/module/
# -------------------------------------------------------------------------------------

[[imports]]
path = "github.com/hugo-fixit/FixIt"

[[imports]]
path = "github.com/hugo-fixit/shortcode-docs-bookmark"

[hugoVersion]
extended = true
min = "0.147.7"
